deployments:
  guestbook:
    kubernetes_manifest: guestbook/frontend-deployment.yaml, guestbook/redis-master-deployment.yaml, guestbook/redis-master-service.yaml, guestbook/frontend-service.yaml
    kubernetes_service: frontend
    deployment_type: kubernetes
    kubernetes_default_image: frontend
  cassandra:
    kubernetes_manifest: cassandra/cassandra-service.yaml, cassandra/cassandra-statefulset.yaml
    deployment_type: kubernetes
    kubernetes_default_image: cassandra
  mysql-wordpress-pd:
    kubernetes_kustomization: mysql-wordpress-pd/
    deployment_type: kubernetes
    kubernetes_service: wordpress
    kubernetes_default_image: wordpress
