deployments:
  guestbook:
    kubernetes_config: guestbook/frontend-deployment.yaml, guestbook/redis-master-deployment.yaml, guestbook/redis-master-service.yaml, guestbook/frontend-service.yaml
    kubernetes_service: frontend
    deployment_type: kubernetes
    kubernetes_default_image: frontend
  cassandra:
    kubernetes_config: cassandra/cassandra-service.yaml, guestbook/redis-master-service.yaml
    deployment_type: kubernetes
    kubernetes_default_image: rss-site
    kubernetes_port_mapping: redmine:3000
    subdomain_port_mapping: redmine:3000
  mysql-wordpress-pd:
    kubernetes_kustomization: mysql-wordpress-pd/
    deployment_type: kubernetes
    kubernetes_default_image: rss-site
    kubernetes_port_mapping: redmine:3000
    subdomain_port_mapping: redmine:3000
  
